### ISSUE TITLE
Having a bit of trouble building

### ISSUE THREAD

**Issue by arkD** [Sven65/Slabbo#11]
I forked and cloned your repo. installed IntelliJ idea and then ran mvn install (using maven 3.6.3)

I get these errors:
[WARNING] The POM for org.spigotmc:spigot:jar:1.16.1-R0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for me.minebuilders:clearlag-core:jar:3.1.6 is missing, no dependency information available

I fixed the first error by adding:
        <repository>
            <id>spigot-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
and removing:
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot</artifactId> <-- this should be spigot-api, but that already existed lower in the list
            <version>1.16.1-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>

leaves me with 
[WARNING] The POM for me.minebuilders:clearlag-core:jar:3.1.6 is missing, no dependency information available

the problem seems to be with minebuilders.me, any idea how i can fix?

also, it would be nice to have simple build directions. like:
```
git clone repo
mvn install (version?)
mvn deploy
```
I'm probably missing stuff there, not sure?

**Comment by Sven65** [comment]
Hi, the pom.xml files shouldn't be modified if you want to build Slabbo locally, the reason they say `spigot` instead of `spigot-api` is because Slabbo uses NMS (`net.minecraft.server`), which is only available with locally compiled spigot jars, as they're not allowed to provide hosted NMS code by Mojang. Instead, they provide the `--compile craftbukkit` option with [buildtools](https://www.spigotmc.org/wiki/buildtools/#compile-craftbukkit) to install them.

For the `me.minebuilders.clearlag-core` dependency, it can be resolved by downloading the clearlag jar from spigot and [installing it to maven](https://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html)

**Comment by arkD** [comment]
Thanks but it turns out grief defender has per region permissions so a flag is not nec.
