### ISSUE TITLE
[Feature request] Support for custom currency formats and symbols

### ISSUE THREAD

**Issue by 0x5c** [Sven65/Slabbo#18]
Some economy providers (like EssentialsX) allow defining custom currency symbols and formats (ie: "n.nn£" instead of "$nn").
This would be a great addition to Slabbo and would tie-in nicely with #17.

**Comment by Sven65** [comment]
Basic support for this already exists with https://github.com/Sven65/Slabbo/blob/67fa5066ecf404305be6523ba7735ece92bb4b55/modules/Plugin/src/main/java/xyz/mackan/Slabbo/manager/LocaleManager.java#L123-L125 and https://github.com/Sven65/Slabbo/blob/c0015887cf5cf34d7bd94ee7bc9718c8a71a0a9a/modules/Plugin/src/main/resources/lang.yml#L74

There's no way to use decimal points at the moment though, since Slabbo currently only works with whole numbers.

How do you suggest the template string should look for decimals? (The `"${amount}"` bit)

**Comment by 0x5c** [comment]
I suggest leaving the decimals formatting to what's provided by Vault, it has a call for that. Otherwise, the way format is specified in Essentials' config would be good too.
For the symbol, I suggest adding a placeholder that gets the symbol through Vault.

**Comment by Sven65** [comment]
I'm assuming you're referring to https://github.com/MilkBowl/VaultAPI/blob/68f14eca202d9b7f1a0fe5a4dcfcfbe26d4a6a40/src/main/java/net/milkbowl/vault/economy/Economy.java#L62 for the formatting and either `currencyNamePlural` or `currencyNameSingular` for the placeholder symbol?

**Comment by 0x5c** [comment]
Oh yeah, sorry for not linking
Those are indeed what I was talking about

**Comment by Sven65** [comment]
Alright! I'll see what can be done!
